=== api-evangelist/unbounce/json-schema/unbounce-sub_account.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "description" : "Representation of a sub-account entity (API sub-accounts are Unbounce Clients).",
  "type" : "object",
  "additionalProperties" : false,
  "required" : [ "created_at", "domains_count", "id", "account_id", "metadata", "name" ],
  "properties" : {
    "created_at" : {
      "title" : "Generic Date",
      "description" : "RFC 5322, section 3.4.1, compliant date, which means formatted with: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      "type" : "string",
      "format" : "date-time"
    },
    "domains_count" : {
      "type" : "integer"
    },
    "id" : {
      "type" : "string"
    },
    "account_id" : {
      "type" : "string"
    },
    "metadata" : {
      "type" : "object",
      "allOf" : [ {
        "title" : "Entity Metadata",
        "type" : "object",
        "required" : [ "location", "documentation" ],
        "properties" : {
          "location" : {
            "type" : "string",
            "format" : "uri"
          },
          "documentation" : {
            "type" : "string",
            "format" : "uri"
          },
          "related" : {
            "type" : "object"
          }
        }
      }, {
        "type" : "object",
        "required" : [ "related" ],
        "properties" : {
          "related" : {
            "type" : "object",
            "additionalProperties" : false,
            "required" : [ "pages", "page_groups", "domains" ],
            "properties" : {
              "pages" : {
                "type" : "string",
                "format" : "uri"
              },
              "page_groups" : {
                "type" : "string",
                "format" : "uri"
              },
              "domains" : {
                "type" : "string",
                "format" : "uri"
              }
            }
          }
        }
      } ]
    },
    "name" : {
      "type" : "string"
    },
    "website" : {
      "type" : "string"
    }
  }
}

=== api-evangelist/unbounce/examples/unbounce-sub_accounts-sub_account_get.json
{
    "account_id": "1456243",
    "created_at": "2015-12-16T00:34:47.000Z",
    "domains_count": 1,
    "id": "1552433",
    "metadata": {
        "documentation": "https://developer.unbounce.com/api_reference/#id_sub_accounts__sub_account_id_",
        "location": "https://api.unbounce.com/sub_accounts/1552433",
        "related": {
            "domains": "https://api.unbounce.com/sub_accounts/1552433/domains",
            "page_groups": "https://api.unbounce.com/sub_accounts/1552433/page_groups",
            "pages": "https://api.unbounce.com/sub_accounts/1552433/pages"
        }
    },
    "name": "Default Client"
}
