=== api-evangelist/unbounce/json-schema/unbounce-lead.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "description" : "Representation of a single lead entity.",
  "type" : "object",
  "additionalProperties" : false,
  "required" : [ "created_at", "id", "extra_data", "form_data", "metadata", "page_id", "submitter_ip", "variant_id" ],
  "properties" : {
    "created_at" : {
      "title" : "Generic Date",
      "description" : "RFC 5322, section 3.4.1, compliant date, which means formatted with: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      "type" : "string",
      "format" : "date-time"
    },
    "id" : {
      "type" : "string"
    },
    "extra_data" : {
      "type" : "object",
      "additionalProperties" : false,
      "properties" : {
        "rapleaf" : {
          "type" : "object"
        },
        "cookies" : {
          "type" : "object"
        },
        "request_id" : {
          "type" : "string"
        },
        "created_by" : {
          "type" : "string",
          "enum" : [ "api" ]
        }
      }
    },
    "form_data" : {
      "type" : "object"
    },
    "metadata" : {
      "type" : "object",
      "allOf" : [ {
        "title" : "Entity Metadata",
        "type" : "object",
        "required" : [ "location", "documentation" ],
        "properties" : {
          "location" : {
            "type" : "string",
            "format" : "uri"
          },
          "documentation" : {
            "type" : "string",
            "format" : "uri"
          },
          "related" : {
            "type" : "object"
          }
        }
      }, {
        "type" : "object",
        "required" : [ "related" ],
        "properties" : {
          "related" : {
            "type" : "object",
            "additionalProperties" : false,
            "required" : [ "page", "sub_account" ],
            "properties" : {
              "page" : {
                "type" : "string",
                "format" : "uri"
              },
              "sub_account" : {
                "type" : "string",
                "format" : "uri"
              }
            }
          }
        }
      } ]
    },
    "page_id" : {
      "type" : "string"
    },
    "submitter_ip" : {
      "type" : "string"
    },
    "variant_id" : {
      "type" : "string"
    }
  }
}

=== api-evangelist/unbounce/examples/unbounce-leads-lead_get.json
{
    "created_at": "2015-12-16T01:03:52.000Z",
    "extra_data": {},
    "form_data": {
        "company": [
            "Lumber James Canada"
        ],
        "email": [
            "james@lumberjames.com"
        ],
        "name": [
            "Lumber James"
        ],
        "phone_number": [
            "7785669522"
        ]
    },
    "id": "deadbeef-dead-beef-dead-beef00000075",
    "metadata": {
        "documentation": "https://developer.unbounce.com/api_reference/#id_leads__lead_id_",
        "location": "https://api.unbounce.com/leads/deadbeef-dead-beef-dead-beef00000075",
        "related": {
            "page": "https://api.unbounce.com/pages/a0a3ffdf-5965-4ef2-8414-8afcded91f70",
            "sub_account": "https://api.unbounce.com/sub_accounts/1552433"
        }
    },
    "page_id": "a0a3ffdf-5965-4ef2-8414-8afcded91f70",
    "submitter_ip": "38.88.7.98",
    "variant_id": "a"
}
