=== api-evangelist/unbounce/json-schema/unbounce-page.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "description" : "Representation of a single page entity, which includes page statistics such as which variant is the winner or loser.",
  "type" : "object",
  "additionalProperties" : false,
  "required" : [ "created_at", "domain", "id", "integrations", "integrations_count", "integrations_errors_count", "metadata", "name", "state", "sub_account_id", "url", "variants_count" ],
  "properties" : {
    "integrations_count" : {
      "type" : "integer"
    },
    "url" : {
      "type" : "string",
      "format" : "uri"
    },
    "sub_account_id" : {
      "type" : "string"
    },
    "id" : {
      "type" : "string"
    },
    "name" : {
      "type" : "string"
    },
    "variants_count" : {
      "type" : "integer"
    },
    "integrations_errors_count" : {
      "type" : "integer"
    },
    "domain" : {
      "type" : "string"
    },
    "metadata" : {
      "type" : "object",
      "allOf" : [ {
        "title" : "Entity Metadata",
        "type" : "object",
        "required" : [ "location", "documentation" ],
        "properties" : {
          "location" : {
            "type" : "string",
            "format" : "uri"
          },
          "documentation" : {
            "type" : "string",
            "format" : "uri"
          },
          "related" : {
            "type" : "object"
          }
        }
      }, {
        "type" : "object",
        "required" : [ "related" ],
        "properties" : {
          "related" : {
            "type" : "object",
            "additionalProperties" : false,
            "required" : [ "form_fields", "leads", "sub_account" ],
            "properties" : {
              "form_fields" : {
                "type" : "string",
                "format" : "uri"
              },
              "leads" : {
                "type" : "string",
                "format" : "uri"
              },
              "sub_account" : {
                "type" : "string",
                "format" : "uri"
              }
            }
          }
        }
      } ]
    },
    "state" : {
      "type" : "string",
      "enum" : [ "unpublished", "published" ]
    },
    "tests" : {
      "$schema" : "http://json-schema.org/draft-04/schema#",
      "description" : "Representation of a campaign experiment, aka a test.",
      "type" : "object",
      "additionalProperties" : false,
      "required" : [ "current" ],
      "properties" : {
        "current" : {
          "oneOf" : [ {
            "type" : "object",
            "additionalProperties" : false
          }, {
            "type" : "object",
            "additionalProperties" : false,
            "required" : [ "champion", "clicks", "conversion_rate", "conversion_rate_delta", "conversions", "form_submits", "has_results", "id", "losers", "visitors", "visits", "winner" ],
            "properties" : {
              "form_submits" : {
                "type" : "integer"
              },
              "visits" : {
                "type" : "integer"
              },
              "conversion_rate" : {
                "type" : "number"
              },
              "clicks" : {
                "type" : "integer"
              },
              "id" : {
                "type" : "string"
              },
              "conversions" : {
                "type" : "integer"
              },
              "losers" : {
                "type" : "string"
              },
              "has_results" : {
                "type" : "boolean"
              },
              "winner" : {
                "type" : "string"
              },
              "champion" : {
                "type" : "string"
              },
              "visitors" : {
                "type" : "integer"
              },
              "conversion_rate_delta" : {
                "type" : "number"
              }
            }
          } ]
        }
      },
      "definitions" : {
        "empty_stats" : {
          "type" : "object",
          "additionalProperties" : false
        },
        "stats" : {
          "type" : "object",
          "additionalProperties" : false,
          "required" : [ "champion", "clicks", "conversion_rate", "conversion_rate_delta", "conversions", "form_submits", "has_results", "id", "losers", "visitors", "visits", "winner" ],
          "properties" : {
            "form_submits" : {
              "type" : "integer"
            },
            "visits" : {
              "type" : "integer"
            },
            "conversion_rate" : {
              "type" : "number"
            },
            "clicks" : {
              "type" : "integer"
            },
            "id" : {
              "type" : "string"
            },
            "conversions" : {
              "type" : "integer"
            },
            "losers" : {
              "type" : "string"
            },
            "has_results" : {
              "type" : "boolean"
            },
            "winner" : {
              "type" : "string"
            },
            "champion" : {
              "type" : "string"
            },
            "visitors" : {
              "type" : "integer"
            },
            "conversion_rate_delta" : {
              "type" : "number"
            }
          }
        }
      }
    },
    "created_at" : {
      "title" : "Generic Date",
      "description" : "RFC 5322, section 3.4.1, compliant date, which means formatted with: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      "type" : "string",
      "format" : "date-time"
    },
    "last_published_at" : {
      "title" : "Generic Date",
      "description" : "RFC 5322, section 3.4.1, compliant date, which means formatted with: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
      "type" : "string",
      "format" : "date-time"
    },
    "integrations" : {
      "type" : "array",
      "minItems" : 0,
      "uniqueItems" : true,
      "items" : {
        "$schema" : "http://json-schema.org/draft-04/schema#",
        "description" : "Representation of a single integration entity.",
        "type" : "object",
        "additionalProperties" : false,
        "required" : [ "type", "errors_count" ],
        "properties" : {
          "type" : {
            "type" : "string"
          },
          "errors_count" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}

=== api-evangelist/unbounce/examples/unbounce-pages-page_get.json
{
    "created_at": "2015-12-16T00:59:29.000Z",
    "domain": "unbouncepages.com",
    "id": "a0a3ffdf-5965-4ef2-8414-8afcded91f70",
    "integrations": [],
    "integrations_count": 0,
    "integrations_errors_count": 0,
    "last_published_at": "2015-12-16T01:02:23.000Z",
    "metadata": {
        "documentation": "https://developer.unbounce.com/api_reference/#id_pages",
        "location": "https://api.unbounce.com/pages/a0a3ffdf-5965-4ef2-8414-8afcded91f70",
        "related": {
            "form_fields": "https://api.unbounce.com/pages/a0a3ffdf-5965-4ef2-8414-8afcded91f70/form_fields",
            "leads": "https://api.unbounce.com/pages/a0a3ffdf-5965-4ef2-8414-8afcded91f70/leads",
            "sub_account": "https://api.unbounce.com/sub_accounts/1552433"
        }
    },
    "name": "Forward Marketing Solutions",
    "state": "published",
    "sub_account_id": "1552433",
    "tests": {
        "current": {
            "champion": "a",
            "clicks": 0,
            "conversion_rate": 33.33,
            "conversion_rate_delta": 0.0,
            "conversions": 1,
            "form_submits": 2,
            "has_results": false,
            "id": "a0a3ffdf-5965-4ef2-8414-8afcded91f70",
            "losers": "",
            "visitors": 3,
            "visits": 3,
            "winner": ""
        }
    },
    "url": "http://unbouncepages.com/forward-marketing-solutions/",
    "variants_count": 0
}
